version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: cinelog-db
    volumes:
      - /root/cinelogdb:/data/db
    ports:
      - "27017:27017"
  api:
    image: eclipse-temurin:17-jdk 
    container_name: cinelog-api
    volumes:
      - ../server.jar:/app/server.jar 
    working_dir: /app
    command: [ "java", "-jar", "server.jar" ]
    ports:
      - "8080:8080" 
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
